**Importing The Libraries**

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

 **Importing The Dataset**

In [4]:
traindataset=pd.read_csv('train_data.csv')
x= traindataset.iloc[:,2:6].values
y=traindataset.iloc[:,-1].values
testdataset=pd.read_csv('unique.csv')
x_unique=testdataset.iloc[:,2:]

**Splitting  The Dataset**

In [5]:
# from sklearn.model_selection import train_test_split
# x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2, random_state=0)

**Training The Random Forest Model**

In [6]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators=1000,random_state=0)
regressor.fit(x,y)

RandomForestRegressor(n_estimators=1000, random_state=0)

**Predicting The Values**

In [7]:
y_pred=[]
for i in x:
  l=[i]
  sample=regressor.predict(l)
  y_pred.append(sample)
y_pred

[array([26.57476667]),
 array([28.47770686]),
 array([24.60555516]),
 array([25.41704484]),
 array([31.05399683]),
 array([31.13413969]),
 array([38.9732105]),
 array([26.57476667]),
 array([28.47770686]),
 array([24.60555516]),
 array([25.41704484]),
 array([31.05399683]),
 array([31.13413969]),
 array([38.9732105]),
 array([26.57476667]),
 array([28.47770686]),
 array([24.60555516]),
 array([25.41704484]),
 array([31.05399683]),
 array([31.13413969]),
 array([38.9732105]),
 array([26.57476667]),
 array([28.47770686]),
 array([24.60555516]),
 array([25.41704484]),
 array([31.05399683]),
 array([31.13413969]),
 array([38.9732105]),
 array([70.70123291]),
 array([61.00339136]),
 array([62.07523973]),
 array([62.72857143]),
 array([71.76751223]),
 array([88.84560059]),
 array([99.75010131]),
 array([70.70123291]),
 array([61.00339136]),
 array([62.07523973]),
 array([62.72857143]),
 array([71.76751223]),
 array([88.84560059]),
 array([99.75010131]),
 array([70.70123291]),
 array([61.0033

**Displaying Actual Values VS Predicted Values**

In [8]:
y_pred_df = pd.DataFrame({'Actual Value':y,'Predicted Values': y_pred})
y_pred_df

Actual Value      Predicted Values
0              22   [26.57476666666668]
1              36  [28.477706859806894]
2              32   [24.60555515873015]
3              26  [25.417044841269846]
4              37    [31.0539968253968]
..            ...                   ...
449            10   [6.153265656565659]
450             5  [13.975789740814726]
451             0  [10.817317534426357]
452            14  [13.562757740870266]
453            19  [32.641682419949284]

[454 rows x 2 columns]

**Checking The Accuracy**

In [9]:
from sklearn.metrics import r2_score
print('Accuracy: %.2f'% r2_score(y,y_pred))

Accuracy: 0.76


**Finding The Delay Time Of The New Data**

In [10]:
y_unique= regressor.predict(x_unique)
print(y_unique)

[ 26.57476667  28.47770686  24.60555516  25.41704484  31.05399683
  31.13413969  38.9732105   26.57476667  28.47770686  24.60555516
  25.41704484  31.05399683  31.13413969  38.9732105   26.57476667
  28.47770686  24.60555516  25.41704484  31.05399683  31.13413969
  38.9732105   70.70123291  61.00339136  62.07523973  62.72857143
  71.76751223  88.84560059  99.75010131  70.70123291  61.00339136
  62.07523973  62.72857143  71.76751223  88.84560059  99.75010131
  70.70123291  61.00339136  62.07523973  62.72857143  71.76751223
  88.84560059  99.75010131  70.70123291  61.00339136  62.07523973
  62.72857143  71.76751223  88.84560059  99.75010131  70.70123291
  61.00339136  62.07523973  62.72857143  71.76751223  88.84560059
  99.75010131  70.70123291  61.00339136  62.07523973  62.72857143
  71.76751223  88.84560059  99.75010131  70.70123291  61.00339136
  62.07523973  62.72857143  71.76751223  88.84560059  99.75010131
  70.70123291  61.00339136  62.07523973  62.72857143  71.76751223
  88.84560

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:439: UserWarning: X has feature names, but RandomForestRegressor was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"


**Displaying the Predicted Values of the Unique Data**

In [11]:
y_unique_df = pd.DataFrame({'Predicted Values': y_unique})
y_unique_df

Predicted Values
0           26.574767
1           28.477707
2           24.605555
3           25.417045
4           31.053997
..                ...
238          6.153266
239         13.975790
240         10.817318
241         13.562758
242         32.641682

[243 rows x 1 columns]

**Saving the model**

In [15]:
import pickle
filename= 'train_model.pkl'
pickle.dump(regressor,open(filename,'wb'))

**Loading Model**

In [13]:
loaded_model=pickle.load(open(filename,'rb'))
y_loaded=loaded_model.predict(x_unique)
print(y_loaded)

[ 26.57476667  28.47770686  24.60555516  25.41704484  31.05399683
  31.13413969  38.9732105   26.57476667  28.47770686  24.60555516
  25.41704484  31.05399683  31.13413969  38.9732105   26.57476667
  28.47770686  24.60555516  25.41704484  31.05399683  31.13413969
  38.9732105   70.70123291  61.00339136  62.07523973  62.72857143
  71.76751223  88.84560059  99.75010131  70.70123291  61.00339136
  62.07523973  62.72857143  71.76751223  88.84560059  99.75010131
  70.70123291  61.00339136  62.07523973  62.72857143  71.76751223
  88.84560059  99.75010131  70.70123291  61.00339136  62.07523973
  62.72857143  71.76751223  88.84560059  99.75010131  70.70123291
  61.00339136  62.07523973  62.72857143  71.76751223  88.84560059
  99.75010131  70.70123291  61.00339136  62.07523973  62.72857143
  71.76751223  88.84560059  99.75010131  70.70123291  61.00339136
  62.07523973  62.72857143  71.76751223  88.84560059  99.75010131
  70.70123291  61.00339136  62.07523973  62.72857143  71.76751223
  88.84560

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:439: UserWarning: X has feature names, but RandomForestRegressor was fitted without feature names
  f"X has feature names, but {self.__class__.__name__} was fitted without"
